[package]
name = "caps"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
projections = { path = "../projections", version = "0.1.0" }
principal = { path = "../principal", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
sqlx = { workspace = true, features = [
    "uuid",
] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
