[package]
name = "game_event_codec"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
domain = { path = "../domain", version = "0.1.0" }
event_actor = { path = "../event_actor", version = "0.1.0" }
eventstore = { path = "../eventstore", version = "0.1.0" }
serde_json = "1"
sqlx = { workspace = true }
thiserror = "1"
uuid = { version = "1", features = ["serde"] }
