[package]
name = "wire"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
commands = { path = "../commands", version = "0.1.0" }
community = { path = "../community", version = "0.1.0" }
projections = { path = "../projections", version = "0.1.0" }
caps = { path = "../caps", version = "0.1.0" }
domain = { path = "../domain", version = "0.1.0" }
game_platform = { path = "../game_platform", version = "0.1.0", features = ["typescript"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts-rs = { version = "12", features = ["uuid-impl"] }
uuid = { version = "1", features = ["v4", "serde"] }
