export const DATABASE_ONE_SHOT_TIMEOUT_VARIABLES = Object.freeze({
  FMARCH_DB_ACQUIRE_TIMEOUT_MS: "30000",
  FMARCH_DB_LOCK_TIMEOUT_MS: "60000",
  FMARCH_DB_STATEMENT_TIMEOUT_MS: "300000",
  FMARCH_DB_OPERATION_TIMEOUT_MS: "600000",
});

export const DATABASE_ONE_SHOT_PLATFORM_WAIT_TIMEOUT_MS = 15 * 60 * 1_000;
