[package]
name = "profile_application"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
eventstore = { path = "../eventstore", version = "0.1.0" }
identity = { path = "../identity", version = "0.1.0" }
profile_handle_index = { path = "../profile_handle_index", version = "0.1.0" }
projections = { path = "../projections", version = "0.1.0" }
serde_json = "1"
social = { path = "../social", version = "0.1.0" }
sqlx = { workspace = true, features = ["uuid", "json"] }
thiserror = "1"
uuid = { version = "1", features = ["v4", "serde"] }
